#!/usr/bin/env bash
# This script reads /etc/passwd and displays specific fields using a while loop

while IFS=':' read -r username password uid gid info home shell
do
    echo "${username}:${uid}:${home}"
done < /etc/passwd
