#!/usr/bin/env bash
# This script lists files in the current directory, cutting out prefixes up to the first dash

for file in *
do
    if [ -f "$file" ]
    then
        echo "${file#*-}"
    fi
done
