#!/usr/bin/env bash
# This script loops infinitely and intercepts SIGTERM signals using a trap

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
